language: go

go:
  - 1.12.x
  - tip

env:
  - GO111MODULE=on

before_install:
  - go mod download

# Only clone the most recent commit.
git:
  depth: 1

script:
 - go vet ./...
 - go test -race -short -v ./...

notifications:
  email:
    - posandrey@gmail.com
