language: go

services:
  - docker

go:
  - 1.12.x
  - tip

env:
  - GO111MODULE=on
  - KAFKA_CONN_STR=192.168.0.50:9092

before_install:
  - sudo ip address add 192.168.0.50/24 dev eth0
  - go mod download

install:
  - docker --version
  - docker pull wurstmeister/zookeeper
  - docker pull wurstmeister/kafka

before_script:
  - docker run -d --name kafka --rm -p 9092:9092 -e KAFKA_ADVERTISED_HOST_NAME="192.168.0.50" -e KAFKA_ZOOKEEPER_CONNECT="192.168.0.50:2181" -v /var/run/docker.sock:/var/run/docker.sock wurstmeister/kafka
  - docker run -d --name zookeeper --rm -p 2181:2181 wurstmeister/zookeeper

after_script:
  - docker stop zookeeper
  - docker stop kafka

# Only clone the most recent commit.
git:
  depth: 1

script:
 - go vet ./...
 - go test -race -v ./...

notifications:
  email:
    - posandrey@gmail.com
