language: go

go:
  - 1.12.x
  - tip

env:
  - GO111MODULE=on
  - ZOOKEEPER_PEERS=localhost:2181
  - KAFKA_PEERS=localhost:9092
before_install:
  - go mod download
  - wget http://www.us.apache.org/dist/kafka/0.8.2.1/kafka_2.10-0.8.2.1.tgz -O kafka.tgz
  - mkdir -p kafka && tar xzf kafka.tgz -C kafka --strip-components 1
  - nohup bash -c "cd kafka && bin/zookeeper-server-start.sh config/zookeeper.properties &"
  - nohup bash -c "cd kafka && bin/kafka-server-start.sh config/server.properties &"
  - sleep 5

# Only clone the most recent commit.
git:
  depth: 1

script:
 - go vet ./...
 - go test -race -v ./...

notifications:
  email:
    - posandrey@gmail.com
