// Code generated by protoc-gen-go. DO NOT EDIT.
// source: access_proxy/accessProxy.proto

package access_proxy

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	voltha "github.com/opencord/voltha-protos/go/voltha"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the serial number
type SerialNumber struct {
	Sn                   string   `protobuf:"bytes,1,opt,name=sn,proto3" json:"sn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SerialNumber) Reset()         { *m = SerialNumber{} }
func (m *SerialNumber) String() string { return proto.CompactTextString(m) }
func (*SerialNumber) ProtoMessage()    {}
func (*SerialNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7bfc5b680edd544, []int{0}
}

func (m *SerialNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SerialNumber.Unmarshal(m, b)
}
func (m *SerialNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SerialNumber.Marshal(b, m, deterministic)
}
func (m *SerialNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SerialNumber.Merge(m, src)
}
func (m *SerialNumber) XXX_Size() int {
	return xxx_messageInfo_SerialNumber.Size(m)
}
func (m *SerialNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_SerialNumber.DiscardUnknown(m)
}

var xxx_messageInfo_SerialNumber proto.InternalMessageInfo

func (m *SerialNumber) GetSn() string {
	if m != nil {
		return m.Sn
	}
	return ""
}

func init() {
	proto.RegisterType((*SerialNumber)(nil), "access_proxy.SerialNumber")
}

func init() { proto.RegisterFile("access_proxy/accessProxy.proto", fileDescriptor_b7bfc5b680edd544) }

var fileDescriptor_b7bfc5b680edd544 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4b, 0x4c, 0x4e, 0x4e,
	0x2d, 0x2e, 0x8e, 0x2f, 0x28, 0xca, 0xaf, 0xa8, 0xd4, 0x87, 0x70, 0x02, 0x40, 0x6c, 0xbd, 0x82,
	0xa2, 0xfc, 0x92, 0x7c, 0x21, 0x1e, 0x64, 0x79, 0x29, 0xa9, 0xb2, 0xfc, 0x9c, 0x92, 0x8c, 0xc4,
	0x78, 0xb0, 0x5c, 0xb1, 0x7e, 0x4a, 0x6a, 0x59, 0x66, 0x72, 0x2a, 0x44, 0xa5, 0x92, 0x1c, 0x17,
	0x4f, 0x70, 0x6a, 0x51, 0x66, 0x62, 0x8e, 0x5f, 0x69, 0x6e, 0x52, 0x6a, 0x91, 0x10, 0x1f, 0x17,
	0x53, 0x71, 0x9e, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x53, 0x71, 0x9e, 0x91, 0x07, 0x17,
	0xbb, 0x0b, 0x58, 0x7d, 0xb1, 0x90, 0x2d, 0x17, 0xaf, 0x7b, 0x6a, 0x09, 0x84, 0xe7, 0x54, 0x19,
	0x9c, 0x27, 0x24, 0xa5, 0x87, 0x6c, 0x8d, 0x1e, 0xb2, 0x39, 0x52, 0x7c, 0x7a, 0x10, 0x4b, 0xf5,
	0x20, 0xea, 0x95, 0x18, 0x9c, 0x0c, 0xb8, 0xa4, 0x32, 0xf3, 0xf5, 0xd2, 0x8b, 0x0a, 0x92, 0x51,
	0xb4, 0x41, 0x5c, 0xe5, 0x24, 0xe0, 0x88, 0xf0, 0x44, 0x00, 0x48, 0x24, 0x80, 0x31, 0x89, 0x0d,
	0x2c, 0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x4a, 0x81, 0x24, 0xee, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DevicesClient is the client API for Devices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DevicesClient interface {
	GetDeviceBySn(ctx context.Context, in *SerialNumber, opts ...grpc.CallOption) (*voltha.Device, error)
}

type devicesClient struct {
	cc *grpc.ClientConn
}

func NewDevicesClient(cc *grpc.ClientConn) DevicesClient {
	return &devicesClient{cc}
}

func (c *devicesClient) GetDeviceBySn(ctx context.Context, in *SerialNumber, opts ...grpc.CallOption) (*voltha.Device, error) {
	out := new(voltha.Device)
	err := c.cc.Invoke(ctx, "/access_proxy.Devices/GetDeviceBySn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DevicesServer is the server API for Devices service.
type DevicesServer interface {
	GetDeviceBySn(context.Context, *SerialNumber) (*voltha.Device, error)
}

func RegisterDevicesServer(s *grpc.Server, srv DevicesServer) {
	s.RegisterService(&_Devices_serviceDesc, srv)
}

func _Devices_GetDeviceBySn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SerialNumber)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServer).GetDeviceBySn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/access_proxy.Devices/GetDeviceBySn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServer).GetDeviceBySn(ctx, req.(*SerialNumber))
	}
	return interceptor(ctx, in, info, handler)
}

var _Devices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "access_proxy.Devices",
	HandlerType: (*DevicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDeviceBySn",
			Handler:    _Devices_GetDeviceBySn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "access_proxy/accessProxy.proto",
}
